/** Simplified Chinese for every piece of site text. The English text is the key; event content is never translated. */
export const ZH: Record<string, string> = {
  // header, footer
  'Skip to content': '跳到主要内容',
  'Campus Radar home': 'Campus Radar 首页',
  'Main navigation': '主导航',
  Explore: '发现',
  Saved: '收藏',
  'Switch language': '切换语言',
  'Browser storage is unavailable. Saves will last only until this page closes.': '浏览器存储不可用,收藏只在关闭本页前有效。',
  'Campus Radar · Events for Northwestern students.': 'Campus Radar · 西北大学学生活动。',
  'Source status': '数据源状态',
  'An independent student project, not affiliated with Northwestern University.': '独立的学生项目,与西北大学无官方关系。',

  // filters
  Today: '今天',
  'This weekend': '本周末',
  'On campus': '校内',
  'On campus only': '仅校内',
  'Free only': '仅免费',
  Time: '时间',
  Category: '类别',
  Map: '地图',
  Cards: '卡片',
  'Show cards': '显示卡片',
  'Show map': '显示地图',
  All: '全部',
  None: '无',
  '{0} selected': '已选 {0} 项',
  '1 selected': '已选 1 项',
  'Next 7 days': '未来 7 天',
  'This week': '本周',
  'This month': '本月',
  'Custom date': '自定义日期',
  'Pick dates': '选择日期',
  'Previous month': '上个月',
  'Next month': '下个月',
  Clear: '清除',
  'Tap a date, or two for a range': '点一个日期,或点两个选一段时间',
  'Tap a later date to choose a range': '再点一个之后的日期,选一段时间',
  Music: '音乐',
  Arts: '艺术',
  Activities: '玩乐',
  Fests: '市集',
  Parties: '派对',
  Event: '活动',
  Sports: '运动',
  Academic: '学术',
  Social: '社交',
  Food: '美食',
  Market: '市集',
  Exhibition: '展览',
  'Shows & Games': '演出/比赛',
  Play: '游乐',
  Other: '其他',
  Evanston: '埃文斯顿',
  Chicago: '芝加哥',
  '(changed)': '(已修改)',

  // search
  'Search events': '搜索活动',
  'Search events (searching for “{0}”)': '搜索活动(当前搜索“{0}”)',
  'Search events…': '搜索活动…',
  'Clear search': '清除搜索',
  Search: '搜索',

  // home
  Events: '活动',
  "This week's picks": '本周精选',
  'Previous poster': '上一张海报',
  'Next poster': '下一张海报',
  'Poster for {0}': '{0} 的海报',
  '{0} event': '{0} 活动',
  'View {0}': '查看 {0}',
  'Loading events': '正在加载活动',
  'Events unavailable': '活动暂时无法显示',
  '{0} events · {1} shown': '共 {0} 个活动 · 已显示 {1} 个',
  '0 events': '0 个活动',
  "Couldn't load events": '无法加载活动',
  'Check your connection and try again.': '请检查网络后重试。',
  'Try again': '重试',
  'Nothing selected': '未选择任何筛选项',
  'No events match your filters': '没有符合筛选条件的活动',
  'No events in the next 7 days': '未来 7 天暂无活动',
  'Reset filters': '重置筛选',
  'Try another date, category, or area.': '试试其他日期、类别或区域。',
  'Showing mapped events in your selected area. Unmapped venues are excluded.': '正在显示所选区域内已标注的活动,未标注地点的活动不包括在内。',
  'Clear area': '清除区域',
  "Couldn't load more events.": '无法加载更多活动。',
  "Couldn't refresh events.": '无法刷新活动。',
  'Loading more events…': '正在加载更多…',
  'Scroll for more events': '向下滑动查看更多',
  'You’ve seen all events matching these filters.': '已显示全部符合条件的活动。',

  // map
  'Event map': '活动地图',
  'Loading Google Maps…': '正在加载谷歌地图…',
  'Search this area': '搜索此区域',
  'Near me': '我附近',
  'Locating…': '正在定位…',
  'At this venue': '此地点的活动',
  'Close venue events': '关闭地点活动',

  // cards
  Canceled: '已取消',
  'Location not listed': '未列出地点',
  Free: '免费',
  'Price varies': '价格不定',
  'Open source for {0} (opens in a new tab)': '打开 {0} 的来源页面(新标签页)',
  Save: '收藏',
  'Save {0}': '收藏 {0}',
  'Unsave {0}': '取消收藏 {0}',

  // detail
  'Back to events': '返回活动列表',
  'Event details': '活动详情',
  'Close event details': '关闭活动详情',
  Collapse: '收起',
  'Full screen': '全屏',
  'Loading event…': '正在加载活动…',
  "Couldn't load this event": '无法加载此活动',
  "Couldn't load this event.": '无法加载此活动。',
  'Event not found': '未找到活动',
  'Event not found. It may have been removed.': '未找到活动,可能已被移除。',
  'It may have been removed, or the link is wrong.': '活动可能已被移除,或链接有误。',
  'Browse events': '浏览活动',
  'This event has been canceled. Check the organizer’s source page for updates.': '此活动已取消,请查看主办方的来源页面了解最新情况。',
  'View source': '查看来源',
  '(opens in a new tab)': '(新标签页打开)',
  When: '时间',
  Where: '地点',
  Price: '价格',
  '{0} (Central Time)': '{0}(芝加哥时间)',
  Maps: '地图',
  'Add to Google Calendar': '添加到谷歌日历',
  'Google Calendar': '谷歌日历',
  'Download cancellation (.ics)': '下载取消通知 (.ics)',
  'Download .ics': '下载 .ics',
  Share: '分享',
  'Link copied': '链接已复制',
  'Copy link': '复制链接',
  'Copy this link': '复制此链接',
  'Share via…': '通过其他方式分享…',
  'Which dates? · Central Time': '选择日期 · 芝加哥时间',
  'Pick a date, or add an end date for a range. This event runs {0}; days without an event are skipped.': '选择一个日期,或再加一个结束日期选择范围。此活动举办时间为 {0},没有活动的日子会被跳过。',
  Date: '日期',
  'End date (optional)': '结束日期(可选)',
  'No event on that date.': '该日期没有活动。',
  'No event on those dates.': '这些日期没有活动。',
  'Google Calendar adds one date at a time, so several dates download as a calendar file you can import.': '谷歌日历一次只能添加一个日期,多个日期会下载为可导入的日历文件。',
  'Download .ics ({0} date)': '下载 .ics({0} 个日期)',
  'Download .ics ({0} dates)': '下载 .ics({0} 个日期)',
  Cancel: '取消',
  'About this event': '活动介绍',

  // saved
  'Saved events': '收藏的活动',
  'Your saved events': '我收藏的活动',
  'Your plans, in date order. Saved in this browser.': '按日期排列的计划,保存在这个浏览器中。',
  'Loading saved events…': '正在加载收藏…',
  "Couldn't load saved events. Your saves are still here.": '无法加载收藏,你的收藏仍然保留。',
  'No upcoming saved events.': '暂无即将举行的收藏活动。',
  'Find something to do': '去找点有意思的',
  'Past events ({0})': '已结束的活动({0})',
  'No longer available': '已不可用',
  'These events may have been removed by their organizers.': '这些活动可能已被主办方移除。',
  'Unavailable event {0}': '不可用的活动 {0}',
  'Remove saved event {0}': '移除收藏的活动 {0}',
  'Page not found': '页面不存在',
  'That page doesn’t exist.': '这个页面不存在。',
}
